[workspace]
members = [
  "clothoid_curve",
  "clothoid_curve_gui", "clothoid_util", "diff_drive", "test_no_std",
]
resolver = "2"

[patch.crates-io]
clothoid_curve = { path = "clothoid_curve" }
clothoid_curve_gui = { path = "clothoid_curve_gui" }
