[workspace]
members = [
  "clothoid_bezier",
  "clothoid_curve",
  "clothoid_curve_gui", "clothoid_util", "diff_drive", "test_no_std",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[workspace.dependencies.stroke]
git = "https://github.com/lucasw/stroke"
branch = "f32_or_f64_only"
version = "0.6.1"

# [patch.crates-io]
# clothoid_curve = { path = "clothoid_curve" }
# clothoid_curve_gui = { path = "clothoid_curve_gui" }

