[package]
name = "clothoid_util"
version = "0.1.0"
edition = "2024"

[dependencies]
argmin = "0.10.0"
argmin-math = "0.4.0"
argmin-observer-slog = "0.1.0"
clothoid_curve = { path = "../clothoid_curve" }
# env_logger = "0.11.2"
finitediff = "0.1.4"
