[package]
name = "clothoid_curve"
version = "0.3.0"
edition = "2021"
repository = "https://github.com/lucasw/clothoid_curve_rs"
readme = "../README.md"
license = "BSD-3"

[features]

[dependencies]
libm = "0.2.8"
