[package]
name = "clothoid_curve"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lucasw/clothoid_curve_rs"
readme = "../README.md"
license = "BSD-3"

[features]
f64 = []

[dependencies]
